from fastapi import FastAPI
from pydantic import BaseModel
from typing import List, Optional, Dict

app = FastAPI()

class Experience(BaseModel):
    title: str
    company: str
    date: str
    bullets: List[str]

class Project(BaseModel):
    name: str
    tech: str
    bullets: List[str]

class Education(BaseModel):
    degree: str
    institution: str
    date: str
    gpa: Optional[str] = ""

class CallRequest(BaseModel):
    name: str
    email: str
    phone: str
    location: str
    linkedin: Optional[str] = ""
    github: Optional[str] = ""
    summary: str
    skills: Dict[str, List[str]]   # {"Languages": ["Python","SQL"], "Frameworks": [...]}
    experience: List[Experience]
    projects: List[Project]
    education: List[Education]
    certifications: Optional[List[str]] = []

def escape_latex(text: str) -> str:
    """Escape special LaTeX characters."""
    replacements = {
        '&': r'\&', '%': r'\%', '$': r'\$', '#': r'\#',
        '_': r'\_', '{': r'\{', '}': r'\}', '~': r'\textasciitilde{}',
        '^': r'\^{}', '\\': r'\textbackslash{}',
    }
    for char, replacement in replacements.items():
        text = text.replace(char, replacement)
    return text

def build_latex(req: CallRequest) -> str:
    def esc(t): return escape_latex(str(t))

    # Skills section
    skills_lines = ""
    for category, items in req.skills.items():
        skills_lines += f"    \\resumeSkill{{{esc(category)}}}{{{esc(', '.join(items))}}}\n"

    # Experience section
    exp_lines = ""
    for exp in req.experience:
        bullets = "\n".join(f"        \\resumeItem{{{esc(b)}}}" for b in exp.bullets)
        exp_lines += f"""    \\resumeSubheading
      {{{esc(exp.title)}}}{{{esc(exp.date)}}}
      {{{esc(exp.company)}}}{{}}
      \\resumeItemListStart
{bullets}
      \\resumeItemListEnd\n"""

    # Projects section
    proj_lines = ""
    for proj in req.projects:
        bullets = "\n".join(f"        \\resumeItem{{{esc(b)}}}" for b in proj.bullets)
        proj_lines += f"""    \\resumeProjectHeading
      {{\\textbf{{{esc(proj.name)}}} $|$ \\emph{{{esc(proj.tech)}}}}}{{}}
      \\resumeItemListStart
{bullets}
      \\resumeItemListEnd\n"""

    # Education section
    edu_lines = ""
    for edu in req.education:
        gpa_str = f" | GPA: {esc(edu.gpa)}" if edu.gpa else ""
        edu_lines += f"""    \\resumeSubheading
      {{{esc(edu.degree)}}}{{{esc(edu.date)}}}
      {{{esc(edu.institution)}}}{{{esc(gpa_str)}}}\n"""

    # Certifications
    cert_lines = ""
    if req.certifications:
        cert_items = "\n".join(f"    \\resumeItem{{{esc(c)}}}" for c in req.certifications)
        cert_lines = f"""\\section{{Certifications}}
  \\resumeItemListStart
{cert_items}
  \\resumeItemListEnd"""

    # LinkedIn and GitHub
    contact_extra = ""
    if req.linkedin:
        contact_extra += f" $|$ \\href{{{esc(req.linkedin)}}}{{LinkedIn}}"
    if req.github:
        contact_extra += f" $|$ \\href{{{esc(req.github)}}}{{GitHub}}"

    tex = f"""% ============================================================
% Overleaf-ready Resume — generated by Resume Enhancer Agent
% Compile with XeLaTeX or pdfLaTeX on overleaf.com
% Template: Jake's Resume (widely used ATS-friendly LaTeX template)
% ============================================================
\\documentclass[letterpaper,11pt]{{article}}

\\usepackage{{latexsym}}
\\usepackage[empty]{{fullpage}}
\\usepackage{{titlesec}}
\\usepackage{{marvosym}}
\\usepackage[usenames,dvipsnames]{{color}}
\\usepackage{{verbatim}}
\\usepackage{{enumitem}}
\\usepackage[hidelinks]{{hyperref}}
\\usepackage{{fancyhdr}}
\\usepackage[english]{{babel}}
\\usepackage{{tabularx}}
\\input{{glyphtounicode}}

\\pagestyle{{fancy}}
\\fancyhf{{}}
\\fancyfoot{{}}
\\renewcommand{{\\headrulewidth}}{{0pt}}
\\renewcommand{{\\footrulewidth}}{{0pt}}

\\addtolength{{\\oddsidemargin}}{{-0.5in}}
\\addtolength{{\\evensidemargin}}{{-0.5in}}
\\addtolength{{\\textwidth}}{{1in}}
\\addtolength{{\\topmargin}}{{-.5in}}
\\addtolength{{\\textheight}}{{1.0in}}

\\urlstyle{{same}}
\\raggedbottom
\\raggedright
\\setlength{{\\tabcolsep}}{{0in}}

\\titleformat{{\\section}}{{
  \\vspace{{-4pt}}\\scshape\\raggedright\\large
}}{{}}{{0em}}{{}}[\\color{{black}}\\titlerule \\vspace{{-5pt}}]

\\pdfgentounicode=1

% ── Custom commands ──
\\newcommand{{\\resumeItem}}[1]{{
  \\item\\small{{#1 \\vspace{{-2pt}}}}
}}
\\newcommand{{\\resumeSubheading}}[4]{{
  \\vspace{{-2pt}}\\item
    \\begin{{tabular*}}{{0.97\\textwidth}}[t]{{l@{{\\extracolsep{{\\fill}}}}r}}
      \\textbf{{#1}} & #2 \\\\
      \\textit{{\\small#3}} & \\textit{{\\small #4}} \\\\
    \\end{{tabular*}}\\vspace{{-7pt}}
}}
\\newcommand{{\\resumeProjectHeading}}[2]{{
    \\item
    \\begin{{tabular*}}{{0.97\\textwidth}}{{l@{{\\extracolsep{{\\fill}}}}r}}
      \\small#1 & #2 \\\\
    \\end{{tabular*}}\\vspace{{-7pt}}
}}
\\newcommand{{\\resumeSkill}}[2]{{
  \\item \\textbf{{#1:}} #2
}}
\\newcommand{{\\resumeItemListStart}}{{\\begin{{itemize}}}}
\\newcommand{{\\resumeItemListEnd}}{{\\end{{itemize}}\\vspace{{-5pt}}}}
\\newcommand{{\\resumeSubHeadingListStart}}{{\\begin{{itemize}}[leftmargin=0.15in, label={{}}]}}
\\newcommand{{\\resumeSubHeadingListEnd}}{{\\end{{itemize}}}}

% ============================================================
\\begin{{document}}

% ── Header ──
\\begin{{center}}
    {{\\Huge \\scshape {esc(req.name)}}} \\\\ \\vspace{{1pt}}
    \\small {esc(req.phone)} $|$
    \\href{{mailto:{esc(req.email)}}}{{{esc(req.email)}}}{contact_extra} $|$
    {esc(req.location)}
\\end{{center}}

% ── Summary ──
\\section{{Summary}}
{esc(req.summary)}

% ── Technical Skills ──
\\section{{Technical Skills}}
 \\begin{{itemize}}[leftmargin=0.15in, label={{}}]
    \\small{{
{skills_lines}    }}
 \\end{{itemize}}

% ── Experience ──
\\section{{Experience}}
  \\resumeSubHeadingListStart
{exp_lines}  \\resumeSubHeadingListEnd

% ── Projects ──
\\section{{Projects}}
    \\resumeSubHeadingListStart
{proj_lines}    \\resumeSubHeadingListEnd

% ── Education ──
\\section{{Education}}
  \\resumeSubHeadingListStart
{edu_lines}  \\resumeSubHeadingListEnd

{cert_lines}

\\end{{document}}
% ============================================================
% Paste this into overleaf.com → New Project → Blank Project
% Replace contents of main.tex → Click Compile
% ============================================================
"""
    return tex

@app.post("/call")
def generate_latex(req: CallRequest):
    tex = build_latex(req)
    return {
        "latex": tex,
        "filename": "resume_enhanced.tex",
        "instructions": "Paste into overleaf.com → New Project → Blank Project → replace main.tex → Compile",
    }

if __name__ == "__main__":
    import uvicorn
    uvicorn.run(app, host="0.0.0.0", port=8007)